<?php return array (
  'system' => 
  array (
    'paypal_client_id' => NULL,
    'paypal_secret' => NULL,
    'status' => 1,
    'phone' => NULL,
    'meta_title_en' => NULL,
    'meta_title_ar' => NULL,
    'meta_description_en' => NULL,
    'meta_description_ar' => NULL,
    'meta_keyword' => NULL,
    'meta_logo' => NULL,
    'balance_status' => NULL,
    'balance_charge' => NULL,
    'currency_id' => NULL,
    'open_at' => NULL,
    'close_at' => NULL,
    'day_open_en' => NULL,
    'day_open_ar' => NULL,
    'facebook_status' => NULL,
    'facebook_link' => NULL,
    'whatsapp_status' => NULL,
    'whatsapp_link' => NULL,
    'telegram_status' => NULL,
    'telegram_link' => NULL,
    'instagram_status' => NULL,
    'instagram_link' => NULL,
    'twitter_status' => NULL,
    'twitter_link' => NULL,
    'paypal_status' => NULL,
    'owner_name' => NULL,
    'logo' => NULL,
  ),
  '98556efb-e37f-4bc1-ae80-765799cc6289' => 
  array (
    'meta_logo' => 'setting/16749857479609213.jpeg',
    'logo' => 'setting/16749857485055345.jpeg',
    'status' => 1,
    'paypal_client_id' => 'Af0oqKJ_DZfLeCNx3QYONHeNRBMIyKsrzfCiFdP-p68kDehdBEbH3d6_Vrj21eMONkFarGqUH0lHyRUf',
    'paypal_secret' => 'UCpyUZ6heAfbA0VjLBuIwh8XixkJgYQ5S0cX1HfuAtH6lZSq7d1OLN4fZKldxcl4Jjg3Uv938Z3nn',
    'phone' => '0953453454',
    'meta_title' => 
    array (
      'en' => 'Syria Resturant',
      'ar' => 'مطعم عربي',
    ),
    'meta_description' => 
    array (
      'en' => 'it\'s good resturant',
      'ar' => 'أنه مطعم جيد',
    ),
    'meta_keyword' => 'food,cike',
    'balance_status' => 1,
    'balance_charge' => 0.1,
    'currency_id' => '9856ba29-4251-47f4-869e-924698f3364f',
    'open_at' => '9:00 AM',
    'close_at' => '10:00 PM',
    'day_open' => 
    array (
      'en' => 
      array (
        0 => 'sunday',
        1 => 'monday',
        2 => 'wendenday',
      ),
      'ar' => 
      array (
        0 => 'الاحد',
        1 => 'الاثنين',
        2 => 'الاربعاء',
      ),
    ),
    'facebook_status' => 1,
    'facebook_link' => 'https://www.facebook.com',
    'whatsapp_status' => 1,
    'whatsapp_link' => 'https://www.whatsapp.com',
    'telegram_status' => 1,
    'telegram_link' => 'https://www.telegram.com',
    'instagram_status' => 1,
    'instagram_link' => 'https://www.instagram.com',
    'twitter_status' => 1,
    'twitter_link' => 'https://www.telegram.com',
    'paypal_status' => 1,
    'owner_name' => 'The Boss',
  ),
  '9856fe22-0df7-4f84-ac53-261253db8d19' => 
  array (
    'paypal_client_id' => NULL,
    'paypal_secret' => NULL,
    'status' => 1,
    'phone' => NULL,
    'meta_title_en' => NULL,
    'meta_title_ar' => NULL,
    'meta_description_en' => NULL,
    'meta_description_ar' => NULL,
    'meta_keyword' => NULL,
    'meta_logo' => NULL,
    'balance_status' => NULL,
    'balance_charge' => NULL,
    'currency_id' => NULL,
    'open_at' => NULL,
    'close_at' => NULL,
    'day_open_en' => NULL,
    'day_open_ar' => NULL,
    'facebook_status' => NULL,
    'facebook_link' => NULL,
    'whatsapp_status' => NULL,
    'whatsapp_link' => NULL,
    'telegram_status' => NULL,
    'telegram_link' => NULL,
    'instagram_status' => NULL,
    'instagram_link' => NULL,
    'twitter_status' => NULL,
    'twitter_link' => NULL,
    'paypal_status' => NULL,
    'owner_name' => NULL,
    'logo' => NULL,
  ),
);